export const FETCH_LIST_CHARACTER_REQUEST = "FETCH_LIST_CHARACTER_REQUEST";
export const FETCH_LIST_CHARACTER_SUCCESS = "FETCH_LIST_CHARACTER_SUCCESS";
export const FETCH_LIST_CHARACTER_ERROR = "FETCH_LIST_CHARACTER_ERROR";

export const FETCH_CHARACTER_REQUEST = "FETCH_CHARACTER_REQUEST";
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS";
export const FETCH_CHARACTER_ERROR = "FETCH_CHARACTER_ERROR";
